### ISSUE TITLE
ASR calculation

### ISSUE THREAD

**Issue by krishnakanthnakka** [git-disl/ESORICS20-CPL#1]
Dear authors,

Regarding the metric attack success rate (ASR), do you rely on L2-threshold  (I think it is set to 1e-4)  between the original and estimated gradients to define the success rate of the attack? If not, can you please clarify.

Thank you. Your paper is very insightful.

**Comment by krishnakanthnakka** [comment]
Other question from the paper:

In Table 6 (b), attack performance vs the local iterations (T) is reported. In this case, is the batch size (B) set to 1?

**Comment by WenqiWei789** [comment]
> Dear authors,
> 
> Regarding the metric attack success rate (ASR), do you rely on L2-threshold (I think it is set to 1e-4) between the original and estimated gradients to define the success rate of the attack? If not, can you please clarify.
> 
> Thank you. Your paper is very insightful.

Hi Krishna, thanks for your interest of our work. Yes we are relying on the L2 threshold of the gradient to measure the attack success rate of the attack. 

Yes. For the batch size, the attack can happen at instance-level (batch size 1). Yet, the training can use a normal batch size like 4, even though the mini-batch can also converge.
